### ISSUE TITLE
Problem with special character escaping for Android

### ISSUE THREAD

**Issue by DanilAtyukov-dev** [tolgee/tolgee-platform#2967]
We export translations in ANDROID_XML format for our project and we have problems with escaping the apostrophe character and line breaks if there are other special characters in the string. For example, the < character is converted to &lt; as expected, but the apostrophe remains unescaped.

query arguments used:
format=ANDROID_XML
fileStructureTemplate=%7BlanguageTag%7D.%7Bextension%7D

I attach screen shots showing that when there is an angle bracket in a line, the apostrophe and the transition to the next line are no longer escaped.

![Image](https://github.com/user-attachments/assets/25eab5bd-2488-47ad-afa3-df0b6048d447)

![Image](https://github.com/user-attachments/assets/2e89d931-22ae-42ad-a603-d3e3af8bd85e)

![Image](https://github.com/user-attachments/assets/1f5b942e-f65b-40ee-bba0-368d2f933090)

**Comment by DanilAtyukov-dev** [comment]
@JanCizmar Hello! Can you tell me when we can expect a fix? This problem is slowing down our work..

**Comment by Anty0** [comment]
Hi @DanilAtyukov-dev! I'll look into the issue!

Looking at the examples, it won't escape characters as expected when malformed XML is inside a string. This is a fallback behavior when the string's contents cannot be parsed correctly—it will just output the raw string there without doing any escaping (the brackets escaping is then done by the XML library later). Android import/export expects Android strings to contain valid XML containing a subset of Android-supported HTML tags.

I tried to reproduce the issue, and this is the result:
<img width="728" alt="Image" src="https://github.com/user-attachments/assets/e88b9b5b-d74d-4b41-bd14-983ed05ddb5d" />

The question is what we should do with such a string—we can no longer parse it and make sure the XML inside is correct. If XML parsing fails, we might be able to escape special characters, or we can wrap it with CDATA to avoid the issue. What would be your preferred solution, @DanilAtyukov-dev?

**Comment by Anty0** [comment]
In PR #2984, I've implemented a fallback that if a string contains malformed XML, Tolgee will assume it represents one XML text node and treat it as such—special characters will be escaped, and the XML library will escape all brackets. I hope this fixes your issue, @DanilAtyukov-dev!

Here is how the exported example strings look with the PR:
<img width="1226" alt="Image" src="https://github.com/user-attachments/assets/f27ac2bd-d00a-4ef0-8142-cead0982bf02" />

**Comment by DanilAtyukov-dev** [comment]
can you tell me when the update will be released? we still have the same problem
![Image](https://github.com/user-attachments/assets/c09a0ce9-f114-465b-9328-8e60b73d3b5c)

**Comment by Anty0** [comment]
Hi @DanilAtyukov-dev !
The update has already been released! The fix for the issue is available for self-hosted instances starting with version 3.109.2. The fix was deployed to Tolgee Cloud on 13.3.2025.

Just to be sure, I've tested it just now with the string in your screenshot, and this is the output when exported for ANDROID_XML (all other settings/options left at default value):

<img width="912" alt="Image" src="https://github.com/user-attachments/assets/4fb64637-d6de-4b2e-be79-2f85288ddbb2" />

If the issue persists for you, can you provide your project ID (assuming you are using Tolgee Cloud) or server logs (if a self-hosted instance better fits your style)? You can also do so in our Tolgee Slack (https://tolg.ee/slack), where you can DM me. I'll take a closer look at your issue!

**Comment by DanilAtyukov-dev** [comment]
@Anty0 
Sorry, I made a mistake, we are self-hosted old version so I didn't see the changes :D thank you very much!

**Comment by Anty0** [comment]
No worries! I'm glad to hear the issue is just an outdated deployment. I hope your experience will be top-notch after you update your deployment! But if you encounter any issues, don't hesitate to contact us on Slack or here again!
